import React from 'react';
import './Reports.css'; // Import CSS for styling
import Navbar from './Navbar';

const reports = [
  {
    template: 'Financial Reconciliation',
    filters: 'Apr 23rd, 2024 - Jun 18th, 2024',
    generatedOn: 'Jun 18th 2024, 3:47 PM'
  },
  {
    template: 'Financial Reconciliation',
    filters: 'Jun 17th, 2024 - Jun 18th, 2024',
    generatedOn: 'Jun 18th 2024, 9:06 AM'
  }
];

const Reports = () => {
  return (
    <>
    <Navbar />
    
    <div className="reports-container">
      <h1>All Reports</h1>
      <h2>Reports Generated by Me</h2>
      <p>Large reports may take up to 1 hour to generate.</p>
      <table>
        <thead>
          <tr>
            <th>Template Used</th>
            <th>Report Filters</th>
            <th>Generated On</th>
          </tr>
        </thead>
        <tbody>
          {reports.map((report, index) => (
            <tr key={index}>
              <td>{report.template}</td>
              <td>{report.filters}</td>
              <td>{report.generatedOn}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className="rows-per-page">
        Rows per page: <select>
          <option value="5">5</option>
          <option value="10">10</option>
          <option value="20">20</option>
        </select>
      </div>
    </div>
    </>
  );
};

export default Reports;
